spring:
  data:
    mongodb:
#      authentication-database: dbAdmin
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
      database: UserServiceDB
      port: 27017
      host: localhost
  application:
    name: user-service
server:
  port: 8080



